### ISSUE TITLE
Display time format error

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion-plugin-events#16]
2017-08-30 16:55:24 - 2017-08-31 16:55:24
Show
30 B, 2017 16:55 - 31 B, 2017 16:55

**Comment by mikeyjm145** [comment]
I am having this exact problem

**Comment by vbezruchkin** [comment]
Hi

Issue has been resolved in the new version of the plugin. It will be available soon.
https://github.com/intelliants/subrion/issues/573

Cheers
