### ISSUE TITLE
Search by title in grid is not working

### ISSUE THREAD

**Issue by sashagar** [intelliants/subrion-plugin-events#21]
before search:

![bb65a987f0](https://user-images.githubusercontent.com/13992012/34353045-270d9788-ea50-11e7-8b3c-671aa86605eb.jpg)

after search:

![933f42c522](https://user-images.githubusercontent.com/13992012/34353048-2c670ea8-ea50-11e7-83e1-13b13f09ac78.jpg)

**Comment by Frozenpath** [comment]
fixed by @sashagar
