### ISSUE TITLE
White screen in the frontpage to install the plugin events

### ISSUE THREAD

**Issue by olairmarcos** [intelliants/subrion-plugin-events#8]
Hello,
I auditioned in version 4.0.5.10 and 4.1.0 of subrion. When I install the plugin on the site, I have a white screen in the frontpage.

Debug: Version Subrion 4.1.0
Parsing Error: Call to a member function getFuture() on a non-object
on line 10 in file includes/classes/ia.core.php(754) : eval()'d code

Thanks. Good job.

**Comment by ghost** [comment]
Hello Marcos! Thanks for your feedback.

The code is fine. It seems you just need to reinstall the plugin in order the hooks kept in DB get updated.

**Comment by ghost** [comment]
Marcos, please take a note that this plugin is compatible only with the dev version of the script. Please be sure that you use the latest dev version of the script.

**Comment by olairmarcos** [comment]
Thanks for the answer.
I downloaded again the latest version of Subrion 4.1.0 for testing.
Now works perfectly, I do not have the white screen.
Thank you for attention. Good job.
